-- VHDL Entity BCtr_lib.BCtr_sys.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 14:50:51 01/11/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY BCtr_sys IS
  GENERIC( 
    ADDR_WIDTH      : integer range 16 downto 8 := 8;
    N_CHANNELS      : integer range 4 downto 1  := 1;
    CTR_WIDTH       : integer range 32 downto 1 := 16;
    FIFO_ADDR_WIDTH : integer range 10 downto 4 := 9;
    N_BOARDS        : integer range 10 downto 1 := 1;
    FAIL_WIDTH      : integer range 16 downto 0 := 2;
    SW_WIDTH        : integer range 16 downto 0 := 1;
    N_INTERRUPTS    : integer range 16 downto 0 := 1
  );
  PORT( 
    Addr          : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    Ctrl          : IN     std_logic_vector (6 DOWNTO 0);
    Data_o        : IN     std_logic_vector (15 DOWNTO 0);
    PMTs          : IN     std_logic_vector (N_CHANNELS-1 DOWNTO 0);
    Switches      : IN     std_logic_vector (SW_WIDTH-1 DOWNTO 0);
    Trigger       : IN     std_logic;
    clk           : IN     std_logic;
    Data_i        : OUT    std_logic_vector (15 DOWNTO 0);
    Fail_Out      : OUT    std_logic_vector (FAIL_WIDTH-1 DOWNTO 0);
    Flt_CPU_Reset : OUT    std_logic;
    Status        : OUT    std_logic_vector (3 DOWNTO 0)
  );

-- Declarations

END ENTITY BCtr_sys ;

--
-- VHDL Architecture BCtr_lib.BCtr_sys.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 14:50:51 01/11/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF BCtr_sys IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL BdIntr    : std_logic_vector(N_INTERRUPTS-1 DOWNTO 0);
  SIGNAL CmdEnbl   : std_logic;
  SIGNAL CmdStrb   : std_logic;
  SIGNAL Collision : std_logic;
  SIGNAL ExpAck    : std_logic_vector(N_BOARDS-1 DOWNTO 0);
  SIGNAL ExpAddr   : std_logic_vector(ADDR_WIDTH-1 DOWNTO 0);
  SIGNAL ExpRd     : std_logic;
  SIGNAL ExpReset  : std_logic;
  SIGNAL ExpWr     : std_logic;
  SIGNAL INTA      : std_logic;
  SIGNAL RData     : std_logic_vector(16*N_BOARDS-1 DOWNTO 0);
  SIGNAL WData     : std_logic_vector(15 DOWNTO 0);


  -- Component Declarations
  COMPONENT BCtr_sbbd
  GENERIC (
    ADDR_WIDTH      : integer range 16 downto 8 := 8;
    BASE_ADDR       : unsigned(15 DOWNTO 0)     := to_unsigned(16,16);
    N_CHANNELS      : integer range 4 downto 1  := 1;
    CTR_WIDTH       : integer range 32 downto 1 := 16;
    FIFO_ADDR_WIDTH : integer range 10 downto 4 := 9
  );
  PORT (
    ExpAddr  : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd    : IN     std_logic ;
    ExpReset : IN     std_logic ;
    ExpWr    : IN     std_logic ;
    PMTs     : IN     std_logic_vector (N_CHANNELS-1 DOWNTO 0);
    Trigger  : IN     std_logic ;
    WData    : IN     std_logic_vector (15 DOWNTO 0);
    clk      : IN     std_logic ;
    ExpAck   : OUT    std_logic ;
    RData    : OUT    std_logic_vector (15 DOWNTO 0)
  );
  END COMPONENT BCtr_sbbd;
  COMPONENT syscon
  GENERIC (
    BUILD_NUMBER  : std_logic_vector(15 DOWNTO 0) := X"0007";
    INSTRUMENT_ID : std_logic_vector(15 DOWNTO 0) := X"0001";
    N_INTERRUPTS  : integer range 15 downto 0     := 1;
    N_BOARDS      : integer range 15 downto 0     := 1;
    ADDR_WIDTH    : integer range 16 downto 8     := 16;
    INTA_ADDR     : std_logic_vector(15 DOWNTO 0) := X"0001";
    BDID_ADDR     : std_logic_vector(15 DOWNTO 0) := X"0002";
    FAIL_ADDR     : std_logic_vector(15 DOWNTO 0) := X"0004";
    SW_ADDR       : std_logic_vector(15 DOWNTO 0) := X"0005";
    FAIL_WIDTH    : integer range 16 downto 1     := 1;
    SW_WIDTH      : integer range 16 DOWNTO 0     := 16;
    TO_ENABLED    : boolean                       := false
  );
  PORT (
    Addr          : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    BdIntr        : IN     std_logic_vector (N_INTERRUPTS-1 DOWNTO 0);
    Ctrl          : IN     std_logic_vector (6 DOWNTO 0);
    Data_o        : IN     std_logic_vector (15 DOWNTO 0);
    ExpAck        : IN     std_logic_vector (N_BOARDS-1 DOWNTO 0);
    RData         : IN     std_logic_vector (16*N_BOARDS-1 DOWNTO 0);
    Switches      : IN     std_logic_vector (SW_WIDTH-1 DOWNTO 0);
    clk           : IN     std_logic;
    CmdEnbl       : OUT    std_logic;
    CmdStrb       : OUT    std_logic;
    Collision     : OUT    std_logic;
    Data_i        : OUT    std_logic_vector (15 DOWNTO 0);
    ExpAddr       : OUT    std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd         : OUT    std_logic;
    ExpReset      : OUT    std_logic;
    ExpWr         : OUT    std_logic;
    Fail_Out      : OUT    std_logic_vector (FAIL_WIDTH-1 DOWNTO 0);
    Flt_CPU_Reset : OUT    std_logic;
    INTA          : OUT    std_logic;
    Status        : OUT    std_logic_vector (3 DOWNTO 0);
    WData         : OUT    std_logic_vector (15 DOWNTO 0)
  );
  END COMPONENT syscon;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : BCtr_sbbd USE ENTITY BCtr_lib.BCtr_sbbd;
  FOR ALL : syscon USE ENTITY BCtr_lib.syscon;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  U_1 : BCtr_sbbd
    GENERIC MAP (
      ADDR_WIDTH      => ADDR_WIDTH,
      BASE_ADDR       => to_unsigned(16,16),
      N_CHANNELS      => N_CHANNELS,
      CTR_WIDTH       => CTR_WIDTH,
      FIFO_ADDR_WIDTH => FIFO_ADDR_WIDTH
    )
    PORT MAP (
      ExpAddr  => ExpAddr,
      ExpRd    => ExpRd,
      ExpReset => ExpReset,
      ExpWr    => ExpWr,
      PMTs     => PMTs,
      Trigger  => Trigger,
      WData    => WData,
      clk      => clk,
      ExpAck   => ExpAck(0),
      RData    => RData
    );
  U_0 : syscon
    GENERIC MAP (
      BUILD_NUMBER  => X"0001",
      INSTRUMENT_ID => X"0008",
      N_INTERRUPTS  => N_INTERRUPTS,
      N_BOARDS      => N_BOARDS,
      ADDR_WIDTH    => ADDR_WIDTH,
      INTA_ADDR     => X"0001",
      BDID_ADDR     => X"0002",
      FAIL_ADDR     => X"0004",
      SW_ADDR       => X"0005",
      FAIL_WIDTH    => FAIL_WIDTH,
      SW_WIDTH      => SW_WIDTH,
      TO_ENABLED    => false
    )
    PORT MAP (
      clk           => clk,
      Ctrl          => Ctrl,
      Addr          => Addr,
      Data_i        => Data_i,
      Data_o        => Data_o,
      Status        => Status,
      ExpRd         => ExpRd,
      ExpWr         => ExpWr,
      WData         => WData,
      RData         => RData,
      ExpAddr       => ExpAddr,
      ExpAck        => ExpAck,
      BdIntr        => BdIntr,
      Collision     => Collision,
      INTA          => INTA,
      CmdEnbl       => CmdEnbl,
      CmdStrb       => CmdStrb,
      ExpReset      => ExpReset,
      Fail_Out      => Fail_Out,
      Switches      => Switches,
      Flt_CPU_Reset => Flt_CPU_Reset
    );

END ARCHITECTURE struct;
