-- VHDL Entity BCtr_lib.BCtr_Dmux.generatedInstance
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 22:48:41 01/10/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY BCtr_Dmux IS
   PORT( 
      C_Dbar : IN     std_logic;
      CData  : IN     std_logic_vector (15 DOWNTO 0);
      DData  : IN     std_logic_vector (15 DOWNTO 0);
      RData  : OUT    std_logic_vector (15 DOWNTO 0)
   );

END BCtr_Dmux ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BCtr_Dmux IS 
BEGIN


END generatedInstance;
