-- VHDL Entity BCtr_lib.BCtr_syscon_wrapper.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
-- BUILDS:
--   6: 2/20/17 Analog I/O
--   5: 2/5/17  Temps
--   4: 2/3/17  DDR
--   3: 1/23/17 Working well, 9600 Baud, positive edge
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY BCtr_syscon_wrapper IS
  PORT( 
    Addr     : IN     std_logic_vector (7 DOWNTO 0);
    Ctrl     : IN     std_logic_vector (6 DOWNTO 0);
    Data_o   : IN     std_logic_vector (15 DOWNTO 0);
    PMTs     : IN     std_logic_vector (1 DOWNTO 0);
    Trigger  : IN     std_logic;
    clk      : IN     std_logic;
    Data_i   : OUT    std_logic_vector (15 DOWNTO 0);
    Fail     : OUT    std_logic;
    temp_scl : INOUT  std_logic;
    temp_sda : INOUT  std_logic;
    aio_scl  : INOUT  std_logic;
    aio_sda  : INOUT  std_logic;
    aio_scl_mon : OUT std_logic;
    aio_sda_mon : OUT std_logic;
    htr1_cmd : OUT    std_logic;
    htr2_cmd : OUT    std_logic;
    SimPMT   : OUT    std_logic;
    SimTrig  : OUT    std_logic;
    Status   : OUT    std_logic_vector (3 DOWNTO 0)
  );

-- Declarations

END ENTITY BCtr_syscon_wrapper ;

--
-- VHDL Architecture BCtr_lib.BCtr_syscon_wrapper.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF BCtr_syscon_wrapper IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Fail_int : std_logic;


  -- Component Declarations
  COMPONENT BCtr_syscon
  GENERIC (
    BUILD_NUMBER   : std_logic_vector(15 DOWNTO 0) := X"0006";    -- Relative to HCHO
    INSTRUMENT_ID  : std_logic_vector(15 DOWNTO 0) := X"0008";    -- HCHO
    N_INTERRUPTS   : integer range 15 downto 0     := 1;
    N_BOARDS       : integer range 15 downto 0     := 4;
    ADDR_WIDTH     : integer range 16 downto 8     := 8;
    FAIL_WIDTH     : integer range 16 downto 1     := 1;
    SW_WIDTH       : integer range 16 DOWNTO 0     := 1;
    N_CTR_CHANNELS : integer range 4 DOWNTO 0      := 2
  );
  PORT (
    Addr     : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    Ctrl     : IN     std_logic_vector (6 DOWNTO 0);
    Data_o   : IN     std_logic_vector (15 DOWNTO 0);
    PMTs     : IN     std_logic_vector (N_CTR_CHANNELS-1 DOWNTO 0);
    Trigger  : IN     std_logic;
    clk      : IN     std_logic;
    temp_scl : INOUT  std_logic;
    temp_sda : INOUT  std_logic;
    aio_scl  : INOUT  std_logic;
    aio_sda  : INOUT  std_logic;
    aio_scl_mon : OUT std_logic;
    aio_sda_mon : OUT std_logic;
    htr1_cmd : OUT    std_logic;
    htr2_cmd : OUT    std_logic;
    Data_i   : OUT    std_logic_vector (15 DOWNTO 0);
    Fail     : OUT    std_logic;
    SimPMT   : OUT    std_logic;
    SimTrig  : OUT    std_logic;
    Status   : OUT    std_logic_vector (3 DOWNTO 0)
  );
  END COMPONENT BCtr_syscon;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : BCtr_syscon USE ENTITY BCtr_lib.BCtr_syscon;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  top : BCtr_syscon
    GENERIC MAP (
      BUILD_NUMBER   => X"0006",      -- Relative to HCHO
      INSTRUMENT_ID  => X"0008",      -- HCHO
      N_INTERRUPTS   => 0,
      FAIL_WIDTH     => 1,
      SW_WIDTH       => 0
    )
    PORT MAP (
      clk      => clk,
      PMTs     => PMTs,
      Trigger  => Trigger,
      Fail     => Fail_int,
      Ctrl     => Ctrl,
      Addr     => Addr,
      temp_scl => temp_scl,
      temp_sda => temp_sda,
      aio_scl  => aio_scl,
      aio_sda  => aio_sda,
      aio_scl_mon => aio_scl_mon,
      aio_sda_mon => aio_sda_mon,
      htr1_cmd => htr1_cmd,
      htr2_cmd => htr2_cmd,
      Data_i   => Data_i,
      Data_o   => Data_o,
      Status   => Status,
      SimTrig  => SimTrig,
      SimPMT   => SimPMT
    );

  Fail <= Fail_int;
END ARCHITECTURE struct;
