-- VHDL Entity BCtr_lib.mock_ts.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 13:11:17 10/30/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY std;
USE std.textio;

ENTITY mock_ts IS
  GENERIC( 
    I2C_ADDR : std_logic_vector(6 downto 0) := "0010100"
  );
  PORT( 
    clk    : IN     std_logic;
    rst    : IN     std_logic;
    scl    : IN     std_logic;
    tsdata : IN     std_logic_vector (31 DOWNTO 0);
    tsen   : IN     std_logic;
    sda    : INOUT  std_logic
  );

-- Declarations

END ENTITY mock_ts ;

--
-- VHDL Architecture BCtr_lib.mock_ts.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 13:36:21 10/30/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY std;
USE std.textio;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF mock_ts IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL RE    : std_logic;
  SIGNAL en    : std_logic;
  SIGNAL rdata : std_logic_vector(7 DOWNTO 0);
  SIGNAL rdreq : std_logic;
  SIGNAL start : std_logic;
  SIGNAL stop  : std_logic;


  -- Component Declarations
  COMPONENT i2c_slave
  GENERIC (
    I2C_ADDR : std_logic_vector(6 DOWNTO 0) := "1000000"
  );
  PORT (
    clk   : IN     std_logic;
    en    : IN     std_logic;
    rdata : IN     std_logic_vector (7 DOWNTO 0);
    rst   : IN     std_logic;
    scl   : IN     std_logic;
    WE    : OUT    std_logic;
    rdreq : OUT    std_logic;
    start : OUT    std_logic;
    stop  : OUT    std_logic;
    wdata : OUT    std_logic_vector (7 DOWNTO 0);
    RE    : INOUT  std_logic;
    sda   : INOUT  std_logic
  );
  END COMPONENT i2c_slave;
  COMPONENT mock_ts_ctrl
  PORT (
    clk    : IN     std_logic ;
    rdreq  : IN     std_logic ;
    rst    : IN     std_logic ;
    start  : IN     std_logic ;
    stop   : IN     std_logic ;
    tsdata : IN     std_logic_vector (31 DOWNTO 0);
    tsen   : IN     std_logic ;
    RE     : OUT    std_logic ;
    en     : OUT    std_logic ;
    rdata  : OUT    std_logic_vector (7 DOWNTO 0)
  );
  END COMPONENT mock_ts_ctrl;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : i2c_slave USE ENTITY BCtr_lib.i2c_slave;
  FOR ALL : mock_ts_ctrl USE ENTITY BCtr_lib.mock_ts_ctrl;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  slave : i2c_slave
    GENERIC MAP (
      I2C_ADDR => I2C_ADDR
    )
    PORT MAP (
      clk   => clk,
      rdata => rdata,
      rst   => rst,
      scl   => scl,
      en    => en,
      WE    => OPEN,
      start => start,
      stop  => stop,
      wdata => OPEN,
      rdreq => rdreq,
      RE    => RE,
      sda   => sda
    );
  ctrl : mock_ts_ctrl
    PORT MAP (
      clk    => clk,
      rdreq  => rdreq,
      rst    => rst,
      start  => start,
      stop   => stop,
      tsdata => tsdata,
      tsen   => tsen,
      RE     => RE,
      en     => en,
      rdata  => rdata
    );

END ARCHITECTURE struct;
