--
-- VHDL Test Bench BCtr_lib.pps_sbbd_tb.pps_sbbd_tester
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 11:56:16 10/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY pps_sbbd_tb IS
  GENERIC (
    ADDR_WIDTH : integer range 16 downto 8 := 8;
    BASE_ADDR  : unsigned(15 downto 0)     := x"0060";
    CLK_FREQ : unsigned(31 downto 0) := to_unsigned(1000,32)
  );
END ENTITY pps_sbbd_tb;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY BCtr_lib;
USE BCtr_lib.ALL;


ARCHITECTURE rtl OF pps_sbbd_tb IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL clk      : std_logic;
  SIGNAL ExpAck   : std_logic;
  SIGNAL ExpAddr  : std_logic_vector(ADDR_WIDTH-1 DOWNTO 0);
  SIGNAL ExpRd    : std_logic;
  SIGNAL ExpReset : std_logic;
  SIGNAL ExpWr    : std_logic;
  SIGNAL PPS      : std_logic;
  SIGNAL RData    : std_logic_vector(15 DOWNTO 0);
  SIGNAL WData    : std_logic_vector(15 DOWNTO 0);
  SIGNAL SimDone  : std_logic;


  -- Component declarations
  COMPONENT pps_sbbd
    GENERIC (
      ADDR_WIDTH : integer range 16 downto 8 := 8;
      BASE_ADDR  : unsigned(15 downto 0)     := x"0060";
      CLK_FREQ : unsigned(31 DOWNTO 0) := to_unsigned(1000,32)
    );
    PORT (
      clk      : IN     std_logic;
      ExpAck   : OUT    std_logic;
      ExpAddr  : IN     std_logic_vector(ADDR_WIDTH-1 DOWNTO 0);
      ExpRd    : IN     std_logic;
      ExpReset : IN     std_logic;
      ExpWr    : IN     std_logic;
      PPS      : OUT    std_logic;
      RData    : OUT    std_logic_vector(15 DOWNTO 0);
      WData    : IN     std_logic_vector(15 DOWNTO 0)
    );
  END COMPONENT pps_sbbd;

  -- embedded configurations
  -- pragma synthesis_off
  FOR dut_pps_sbbd : pps_sbbd USE ENTITY BCtr_lib.pps_sbbd;
  -- pragma synthesis_on

BEGIN

  dut_pps_sbbd : pps_sbbd
    GENERIC MAP (
      ADDR_WIDTH => ADDR_WIDTH,
      BASE_ADDR  => BASE_ADDR,
      CLK_FREQ => CLK_FREQ
    )
    PORT MAP (
      clk      => clk,
      ExpAck   => ExpAck,
      ExpAddr  => ExpAddr,
      ExpRd    => ExpRd,
      ExpReset => ExpReset,
      ExpWr    => ExpWr,
      PPS      => PPS,
      RData    => RData,
      WData    => WData
    );

  f1k_clk : Process is
  Begin
    clk <= '0';
    -- pragma synthesis_off
    wait for 20 ns;
    while SimDone = '0' loop
      clk <= '1';
      wait for 500 us;
      clk <= '0';
      wait for 500 us;
    end loop;
    wait;
    -- pragma synthesis_on
  End Process;

  test_proc: Process is
  Begin
    SimDone <= '0';
    WData <= (others => '0');
    ExpAddr <= (others => '0');
    ExpRd <= '0';
    ExpWr <= '0';
    ExpReset <= '1';
    -- pragma synthesis_off
    -- might need to reset the circuit here...
    wait until clk'Event and clk = '1';
    wait until clk'Event and clk = '1';
    ExpReset <= '0';
    
    wait until PPS = '1';
    wait until PPS = '0';
    wait until PPS = '1';
    wait until clk'Event and clk = '1';
    wait until clk'Event and clk = '1';

    SimDone <= '1';
    wait;
   -- pragma synthesis_on
  END PROCESS;

END ARCHITECTURE rtl;