-- VHDL Entity BCtr_lib.temp_top_tb.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 17:03:17 10/28/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

USE ieee.numeric_std.ALL;

ENTITY temp_top_tb IS
  GENERIC( 
    BASE_ADDR  : unsigned (15 DOWNTO 0)    := X"0030";
    ADDR_WIDTH : integer range 16 downto 8 := 8      -- 
  );
-- Declarations

END ENTITY temp_top_tb ;

--
-- VHDL Architecture BCtr_lib.temp_top_tb.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 20:10:31 10/30/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY std;
USE std.textio;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF temp_top_tb IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Addr   : std_logic_vector(ADDR_WIDTH-1 DOWNTO 0);
  SIGNAL ExpAck : std_logic;
  SIGNAL ExpRd  : std_logic;
  SIGNAL ExpWr  : std_logic;
  SIGNAL RData  : std_logic_vector(15 DOWNTO 0);
  SIGNAL clk    : std_logic;
  SIGNAL rst    : std_logic;
  SIGNAL scl    : std_logic;
  SIGNAL sda    : std_logic;
  SIGNAL tsdata : std_logic_vector(31 DOWNTO 0);
  SIGNAL tsen14 : std_logic;
  SIGNAL tsen24 : std_logic;


  -- Component Declarations
  COMPONENT mock_ts
  GENERIC (
    I2C_ADDR : std_logic_vector(6 downto 0) := "0010100"
  );
  PORT (
    clk    : IN     std_logic ;
    rst    : IN     std_logic ;
    scl    : IN     std_logic ;
    tsdata : IN     std_logic_vector (31 DOWNTO 0);
    tsen   : IN     std_logic ;
    sda    : INOUT  std_logic 
  );
  END COMPONENT mock_ts;
  COMPONENT temp_top
  GENERIC (
    BASE_ADDR  : unsigned (15 DOWNTO 0)    := X"0000";
    ADDR_WIDTH : integer range 16 downto 8 := 8      -- 
  );
  PORT (
    Addr   : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd  : IN     std_logic ;
    ExpWr  : IN     std_logic ;
    clk    : IN     std_logic ;
    rst    : IN     std_logic ;
    ExpAck : OUT    std_logic ;
    RData  : OUT    std_logic_vector (15 DOWNTO 0);
    scl    : INOUT  std_logic ;
    sda    : INOUT  std_logic 
  );
  END COMPONENT temp_top;
  COMPONENT temp_top_tester
  GENERIC (
    ADDR_WIDTH : integer range 16 downto 8 := 8    --
  );
  PORT (
    ExpAck : IN     std_logic ;
    RData  : IN     std_logic_vector (15 DOWNTO 0);
    Addr   : OUT    std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd  : OUT    std_logic ;
    ExpWr  : OUT    std_logic ;
    clk    : OUT    std_logic ;
    rst    : OUT    std_logic ;
    scl    : INOUT  std_logic ;
    sda    : INOUT  std_logic ;
    tsen24 : OUT    std_logic ;
    tsdata : OUT    std_logic_vector (31 DOWNTO 0);
    tsen14 : OUT    std_logic 
  );
  END COMPONENT temp_top_tester;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : mock_ts USE ENTITY BCtr_lib.mock_ts;
  FOR ALL : temp_top USE ENTITY BCtr_lib.temp_top;
  FOR ALL : temp_top_tester USE ENTITY BCtr_lib.temp_top_tester;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  slave14 : mock_ts
    GENERIC MAP (
      I2C_ADDR => "0010100"
    )
    PORT MAP (
      clk    => clk,
      rst    => rst,
      scl    => scl,
      tsdata => tsdata,
      tsen   => tsen14,
      sda    => sda
    );
  slave24 : mock_ts
    GENERIC MAP (
      I2C_ADDR => "0100100"
    )
    PORT MAP (
      clk    => clk,
      rst    => rst,
      scl    => scl,
      tsdata => tsdata,
      tsen   => tsen24,
      sda    => sda
    );
  DUT : temp_top
    GENERIC MAP (
      BASE_ADDR  => BASE_ADDR,
      ADDR_WIDTH => 8        -- 
    )
    PORT MAP (
      Addr   => Addr,
      ExpRd  => ExpRd,
      ExpWr  => ExpWr,
      clk    => clk,
      rst    => rst,
      ExpAck => ExpAck,
      RData  => RData,
      scl    => scl,
      sda    => sda
    );
  tester : temp_top_tester
    GENERIC MAP (
      ADDR_WIDTH => 8      --
    )
    PORT MAP (
      ExpAck => ExpAck,
      RData  => RData,
      Addr   => Addr,
      ExpRd  => ExpRd,
      ExpWr  => ExpWr,
      clk    => clk,
      rst    => rst,
      scl    => scl,
      sda    => sda,
      tsen24 => tsen24,
      tsdata => tsdata,
      tsen14 => tsen14
    );

END ARCHITECTURE struct;
