-- VHDL Entity BCtr_lib.temp_top_tb.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 17:03:17 10/28/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

USE ieee.numeric_std.ALL;

ENTITY temp_top_tb IS
  GENERIC( 
    BASE_ADDR  : unsigned (15 DOWNTO 0)    := X"0030";
    ADDR_WIDTH : integer range 16 downto 8 := 8      -- 
  );
-- Declarations

END ENTITY temp_top_tb ;

--
-- VHDL Architecture BCtr_lib.temp_top_tb.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 23:05:09 10/28/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY std;
USE std.textio;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF temp_top_tb IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Addr   : std_logic_vector(ADDR_WIDTH-1 DOWNTO 0);
  SIGNAL ExpAck : std_logic;
  SIGNAL ExpRd  : std_logic;
  SIGNAL ExpWr  : std_logic;
  SIGNAL RData  : std_logic_vector(15 DOWNTO 0);
  SIGNAL RE     : std_logic;
  SIGNAL WE     : std_logic;
  SIGNAL clk    : std_logic;
  SIGNAL en     : std_logic;
  SIGNAL rdata1 : std_logic_vector(7 DOWNTO 0);
  SIGNAL rdreq  : std_logic;
  SIGNAL rst    : std_logic;
  SIGNAL scl    : std_logic;
  SIGNAL sda    : std_logic;
  SIGNAL start  : std_logic;
  SIGNAL wdata  : std_logic_vector(7 DOWNTO 0);


  -- Component Declarations
  COMPONENT i2c_slave
  GENERIC (
    I2C_ADDR : std_logic_vector(6 DOWNTO 0) := "1000000"
  );
  PORT (
    clk   : IN     std_logic;
    en    : IN     std_logic;
    rdata : IN     std_logic_vector (7 DOWNTO 0);
    rst   : IN     std_logic;
    scl   : IN     std_logic;
    WE    : OUT    std_logic;
    rdreq : OUT    std_logic;
    start : OUT    std_logic;
    stop  : OUT    std_logic;
    wdata : OUT    std_logic_vector (7 DOWNTO 0);
    RE    : INOUT  std_logic;
    sda   : INOUT  std_logic
  );
  END COMPONENT i2c_slave;
  COMPONENT temp_top
  GENERIC (
    BASE_ADDR  : unsigned (15 DOWNTO 0)    := X"0000";
    ADDR_WIDTH : integer range 16 downto 8 := 8      -- 
  );
  PORT (
    Addr   : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd  : IN     std_logic ;
    ExpWr  : IN     std_logic ;
    clk    : IN     std_logic ;
    rst    : IN     std_logic ;
    ExpAck : OUT    std_logic ;
    RData  : OUT    std_logic_vector (15 DOWNTO 0);
    scl    : INOUT  std_logic ;
    sda    : INOUT  std_logic 
  );
  END COMPONENT temp_top;
  COMPONENT temp_top_tester
  GENERIC (
    ADDR_WIDTH : integer range 16 downto 8 := 8    --
  );
  PORT (
    ExpAck : IN     std_logic ;
    RData  : IN     std_logic_vector (15 DOWNTO 0);
    WE     : IN     std_logic ;
    rdreq  : IN     std_logic ;
    start  : IN     std_logic ;
    wdata  : IN     std_logic_vector (7 DOWNTO 0);
    Addr   : OUT    std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd  : OUT    std_logic ;
    ExpWr  : OUT    std_logic ;
    RE     : OUT    std_logic ;
    clk    : OUT    std_logic ;
    en     : OUT    std_logic ;
    rdata1 : OUT    std_logic_vector (7 DOWNTO 0);
    rst    : OUT    std_logic ;
    scl    : INOUT  std_logic ;
    sda    : INOUT  std_logic 
  );
  END COMPONENT temp_top_tester;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : i2c_slave USE ENTITY BCtr_lib.i2c_slave;
  FOR ALL : temp_top USE ENTITY BCtr_lib.temp_top;
  FOR ALL : temp_top_tester USE ENTITY BCtr_lib.temp_top_tester;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  U_2 : i2c_slave
    GENERIC MAP (
      I2C_ADDR => "0010100"
    )
    PORT MAP (
      clk   => clk,
      rdata => rdata1,
      rst   => rst,
      scl   => scl,
      en    => en,
      WE    => WE,
      start => start,
      stop  => OPEN,
      wdata => wdata,
      rdreq => rdreq,
      RE    => RE,
      sda   => sda
    );
  U_0 : temp_top
    GENERIC MAP (
      BASE_ADDR  => BASE_ADDR,
      ADDR_WIDTH => 8        -- 
    )
    PORT MAP (
      Addr   => Addr,
      ExpRd  => ExpRd,
      ExpWr  => ExpWr,
      clk    => clk,
      rst    => rst,
      ExpAck => ExpAck,
      RData  => RData,
      scl    => scl,
      sda    => sda
    );
  U_1 : temp_top_tester
    GENERIC MAP (
      ADDR_WIDTH => 8      --
    )
    PORT MAP (
      ExpAck => ExpAck,
      RData  => RData,
      WE     => WE,
      rdreq  => rdreq,
      start  => start,
      wdata  => wdata,
      Addr   => Addr,
      ExpRd  => ExpRd,
      ExpWr  => ExpWr,
      RE     => RE,
      clk    => clk,
      en     => en,
      rdata1 => rdata1,
      rst    => rst,
      scl    => scl,
      sda    => sda
    );

END ARCHITECTURE struct;
