-- VHDL Entity BCtr_lib.BCtr_syscon_wrapper.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY BCtr_syscon_wrapper IS
  PORT( 
    Addr    : IN     std_logic_vector (7 DOWNTO 0);
    Ctrl    : IN     std_logic_vector (6 DOWNTO 0);
    Data_o  : IN     std_logic_vector (15 DOWNTO 0);
    PMTs    : IN     std_logic_vector (1 DOWNTO 0);
    Trigger : IN     std_logic;
    clk     : IN     std_logic;
    Data_i  : OUT    std_logic_vector (15 DOWNTO 0);
    Fail    : OUT    std_logic;
    SimPMT  : OUT    std_logic;
    SimTrig : OUT    std_logic;
    Status  : OUT    std_logic_vector (3 DOWNTO 0)
  );

-- Declarations

END ENTITY BCtr_syscon_wrapper ;

--
-- VHDL Architecture BCtr_lib.BCtr_syscon_wrapper.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ARCHITECTURE struct OF BCtr_syscon_wrapper IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Fail_int : std_logic;


  -- Component Declarations
  COMPONENT BCtr_syscon
  GENERIC (
    BUILD_NUMBER   : std_logic_vector(15 DOWNTO 0) := X"0001";    -- Relative to HCHO
    INSTRUMENT_ID  : std_logic_vector(15 DOWNTO 0) := X"0008";    -- HCHO
    N_INTERRUPTS   : integer range 15 downto 0     := 1;
    N_BOARDS       : integer range 15 downto 0     := 2;
    ADDR_WIDTH     : integer range 16 downto 8     := 8;
    FAIL_WIDTH     : integer range 16 downto 1     := 1;
    SW_WIDTH       : integer range 16 DOWNTO 0     := 1;
    N_CTR_CHANNELS : integer range 4 DOWNTO 0      := 2
  );
  PORT (
    Addr    : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    Ctrl    : IN     std_logic_vector (6 DOWNTO 0);
    Data_o  : IN     std_logic_vector (15 DOWNTO 0);
    PMTs    : IN     std_logic_vector (N_CTR_CHANNELS-1 DOWNTO 0);
    Trigger : IN     std_logic;
    clk     : IN     std_logic;
    Data_i  : OUT    std_logic_vector (15 DOWNTO 0);
    Fail    : OUT    std_logic;
    SimPMT  : OUT    std_logic;
    SimTrig : OUT    std_logic;
    Status  : OUT    std_logic_vector (3 DOWNTO 0)
  );
  END COMPONENT BCtr_syscon;

  -- Optional embedded configurations
  -- pragma synthesis_off
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  U_0 : BCtr_syscon
    GENERIC MAP (
      BUILD_NUMBER   => X"0002",      -- Relative to HCHO
      INSTRUMENT_ID  => X"0008",      -- HCHO
      N_INTERRUPTS   => 0,
      N_BOARDS       => 2,
      ADDR_WIDTH     => 8,
      FAIL_WIDTH     => 1,
      SW_WIDTH       => 0,
      N_CTR_CHANNELS => 2
    )
    PORT MAP (
      clk     => clk,
      PMTs    => PMTs,
      Trigger => Trigger,
      Fail    => Fail_int,
      Ctrl    => Ctrl,
      Addr    => Addr,
      Data_i  => Data_i,
      Data_o  => Data_o,
      Status  => Status,
      SimTrig => SimTrig,
      SimPMT  => SimPMT
    );

  Fail <= Fail_int;
END ARCHITECTURE struct;
