--
-- VHDL Test Bench BCtr_lib.BCtr_syscon_wrapper_tb.BCtr_syscon_wrapper_tester
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:41:33 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY BCtr_syscon_wrapper_tb IS
END ENTITY BCtr_syscon_wrapper_tb;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY BCtr_lib;
USE BCtr_lib.ALL;


ARCHITECTURE rtl OF BCtr_syscon_wrapper_tb IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Addr    : std_logic_vector(7 DOWNTO 0);
  SIGNAL Ctrl    : std_logic_vector(6 DOWNTO 0);
  SIGNAL Data_o  : std_logic_vector(15 DOWNTO 0);
  SIGNAL PMTs    : std_logic_vector(1 DOWNTO 0);
  SIGNAL Trigger : std_logic;
  SIGNAL clk     : std_logic;
  SIGNAL Data_i  : std_logic_vector(15 DOWNTO 0);
  SIGNAL Fail    : std_logic;
  SIGNAL SimPMT  : std_logic;
  SIGNAL SimTrig : std_logic;
  SIGNAL Status  : std_logic_vector(3 DOWNTO 0);


  -- Component declarations
  COMPONENT BCtr_syscon_wrapper
    PORT (
      Addr    : IN     std_logic_vector(7 DOWNTO 0);
      Ctrl    : IN     std_logic_vector(6 DOWNTO 0);
      Data_o  : IN     std_logic_vector(15 DOWNTO 0);
      PMTs    : IN     std_logic_vector(1 DOWNTO 0);
      Trigger : IN     std_logic;
      clk     : IN     std_logic;
      Data_i  : OUT    std_logic_vector(15 DOWNTO 0);
      Fail    : OUT    std_logic;
      SimPMT  : OUT    std_logic;
      SimTrig : OUT    std_logic;
      Status  : OUT    std_logic_vector(3 DOWNTO 0)
    );
  END COMPONENT BCtr_syscon_wrapper;

  COMPONENT BCtr_syscon_wrapper_tester
    PORT (
      Addr    : OUT    std_logic_vector(7 DOWNTO 0);
      Ctrl    : OUT    std_logic_vector(6 DOWNTO 0);
      Data_o  : OUT    std_logic_vector(15 DOWNTO 0);
      clk     : OUT    std_logic;
      Data_i  : IN     std_logic_vector(15 DOWNTO 0);
      Status  : IN     std_logic_vector(3 DOWNTO 0)
    );
  END COMPONENT BCtr_syscon_wrapper_tester;

  -- embedded configurations
  -- pragma synthesis_off
  FOR U_0 : BCtr_syscon_wrapper USE ENTITY BCtr_lib.BCtr_syscon_wrapper;
  FOR U_1 : BCtr_syscon_wrapper_tester USE ENTITY BCtr_lib.BCtr_syscon_wrapper_tester;
  -- pragma synthesis_on

BEGIN

    U_0 : BCtr_syscon_wrapper
      PORT MAP (
        Addr    => Addr,
        Ctrl    => Ctrl,
        Data_o  => Data_o,
        PMTs    => PMTs,
        Trigger => Trigger,
        clk     => clk,
        Data_i  => Data_i,
        Fail    => Fail,
        SimPMT  => SimPMT,
        SimTrig => SimTrig,
        Status  => Status
      );

    U_1 : BCtr_syscon_wrapper_tester
      PORT MAP (
        Addr    => Addr,
        Ctrl    => Ctrl,
        Data_o  => Data_o,
        clk     => clk,
        Data_i  => Data_i,
        Status  => Status
      );

  Trigger <= SimTrig;
  PMTs(0) <= SimPMT;
  PMTS(1) <= '0';
END ARCHITECTURE rtl;