-- VHDL Entity BCtr_lib.BCtr_syscon_wrapper.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
-- BUILDS:
--  10: 12/10/17 Cleanup Expired handling, DACscan bits to BCtr,
--               DACscan chopping
--   9: 11/24/17 Fixing IPS Gen lockup (BUILD_NUMBER incorrectly at 8)
--   8: 11/20/17 BCtr2, IPS, PPS
--   7: 10/29/17 Fix temp sensor overflow and wrapping
--      10/16/17 Switch to alternate serial I/O
--   6: 2/20/17 Analog I/O
--   5: 2/5/17  Temps
--   4: 2/3/17  DDR
--   3: 1/23/17 Working well, 9600 Baud, positive edge
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY BCtr_syscon_wrapper IS
  GENERIC(
    BUILD_NUMBER   : std_logic_vector(15 DOWNTO 0) := X"000A";    -- Relative to HCHO
    Nbps_default   : integer range 63 downto 1     := 10
  );
  PORT( 
    Addr      : IN     std_logic_vector (7 DOWNTO 0);
    Ctrl      : IN     std_logic_vector (6 DOWNTO 0);
    Data_o    : IN     std_logic_vector (15 DOWNTO 0);
    PMTs      : IN     std_logic_vector (1 DOWNTO 0);
    Trigger   : IN     std_logic;
    clk       : IN     std_logic;
    Data_i    : OUT    std_logic_vector (15 DOWNTO 0);
    Fail      : OUT    std_logic;
    temp_scl_o : OUT    std_logic;
    temp_scl_i : IN    std_logic;
    temp_sda_o : OUT   std_logic;
    temp_sda_i : IN    std_logic;
    aio_scl_o : OUT    std_logic;
    aio_scl_i : IN     std_logic;
    aio_sda_o : OUT    std_logic;
    aio_sda_i : IN     std_logic;
    htr1_cmd  : OUT    std_logic;
    htr2_cmd  : OUT    std_logic;
    SimPMT    : OUT    std_logic;
    SimTrig   : OUT    std_logic;
    Status    : OUT    std_logic_vector (3 DOWNTO 0);
    dac_reset : OUT   std_logic;
    dac_ldac  : OUT    std_logic
  );

-- Declarations

END ENTITY BCtr_syscon_wrapper ;

--
-- VHDL Architecture BCtr_lib.BCtr_syscon_wrapper.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 12:31:13 01/19/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- LIBRARY BCtr_lib;

ARCHITECTURE struct OF BCtr_syscon_wrapper IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL Fail_int : std_logic;


  -- Component Declarations
  COMPONENT BCtr_syscon
  GENERIC (
    BUILD_NUMBER   : std_logic_vector(15 DOWNTO 0) := X"0008";    -- Relative to HCHO
    INSTRUMENT_ID  : std_logic_vector(15 DOWNTO 0) := X"0008";    -- HCHO
    N_INTERRUPTS   : integer range 15 downto 0     := 1;
    N_BOARDS       : integer range 15 downto 0     := 7;
    ADDR_WIDTH     : integer range 16 downto 8     := 8;
    FAIL_WIDTH     : integer range 16 downto 1     := 1;
    SW_WIDTH       : integer range 16 DOWNTO 0     := 1;
    N_CTR_CHANNELS : integer range 4 DOWNTO 0      := 2;
    Nbps_default   : integer range 63 downto 1     := 10
  );
  PORT (
    Addr      : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    Ctrl      : IN     std_logic_vector (6 DOWNTO 0);
    Data_o    : IN     std_logic_vector (15 DOWNTO 0);
    PMTs      : IN     std_logic_vector (N_CTR_CHANNELS-1 DOWNTO 0);
    Trigger   : IN     std_logic;
    clk       : IN     std_logic;
    temp_scl_o : OUT    std_logic;
    temp_scl_i : IN    std_logic;
    temp_sda_o : OUT   std_logic;
    temp_sda_i : IN    std_logic;
    aio_scl_o  : OUT    std_logic;
    aio_scl_i : IN     std_logic;
    aio_sda_o : OUT    std_logic;
    aio_sda_i : IN     std_logic;
    htr1_cmd : OUT    std_logic;
    htr2_cmd : OUT    std_logic;
    Data_i   : OUT    std_logic_vector (15 DOWNTO 0);
    Fail     : OUT    std_logic;
    SimPMT   : OUT    std_logic;
    SimTrig  : OUT    std_logic;
    Status   : OUT    std_logic_vector (3 DOWNTO 0);
    LDAC     : OUT    std_logic
  );
  END COMPONENT BCtr_syscon;

  -- Optional embedded configurations
  -- pragma synthesis_off
  -- FOR ALL : BCtr_syscon USE ENTITY BCtr_lib.BCtr_syscon;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  top : BCtr_syscon
    GENERIC MAP (
      BUILD_NUMBER   => BUILD_NUMBER,      -- Relative to HCHO
      INSTRUMENT_ID  => X"0008",      -- HCHO
      N_INTERRUPTS   => 0,
      FAIL_WIDTH     => 1,
      SW_WIDTH       => 0,
      N_CTR_CHANNELS => 2,
      Nbps_default   => Nbps_default
    )
    PORT MAP (
      clk      => clk,
      PMTs     => PMTs,
      Trigger  => Trigger,
      Fail     => Fail_int,
      Ctrl     => Ctrl,
      Addr     => Addr,
      temp_scl_o => temp_scl_o,
      temp_scl_i => temp_scl_i,
      temp_sda_o => temp_sda_o,
      temp_sda_i => temp_sda_i,
      aio_scl_o => aio_scl_o,
      aio_scl_i => aio_scl_i,
      aio_sda_o => aio_sda_o,
      aio_sda_i => aio_sda_i,
      htr1_cmd => htr1_cmd,
      htr2_cmd => htr2_cmd,
      Data_i   => Data_i,
      Data_o   => Data_o,
      Status   => Status,
      SimTrig  => SimTrig,
      SimPMT   => SimPMT,
      LDAC     => dac_ldac
    );

  Fail <= Fail_int;
  dac_reset <= '1';
END ARCHITECTURE struct;
