-- VHDL Entity BCtr_lib.ips_sbbd.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 13:46:36 11/11/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY ips_sbbd IS
  GENERIC( 
    ADDR_WIDTH : integer range 16 downto 8 := 8;
    BASE_ADDR  : unsigned(15 DOWNTO 0)     := x"0070"
  );
  PORT( 
    ExpAddr  : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    ExpRd    : IN     std_logic;
    ExpReset : IN     std_logic;
    ExpWr    : IN     std_logic;
    PPS      : IN     std_logic;
    WData    : IN     std_logic_vector (15 DOWNTO 0);
    clk      : IN     std_logic;
    ExpAck   : OUT    std_logic;
    IPS      : OUT    std_logic;
    IPnum    : OUT    std_logic_vector (5 DOWNTO 0);
    RData    : OUT    std_logic_vector (15 DOWNTO 0)
  );

-- Declarations

END ENTITY ips_sbbd ;

--
-- VHDL Architecture BCtr_lib.ips_sbbd.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-XPS14)
--          at - 13:46:36 11/11/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--

-- Generation properties:
--   Component declarations : yes
--   Configurations         : embedded statements
--                          : add pragmas
--                          : exclude view name
--   
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY BCtr_lib;

ARCHITECTURE struct OF ips_sbbd IS

  -- Architecture declarations

  -- Internal signal declarations
  SIGNAL BdEn   : std_logic;
  SIGNAL BdWrEn : std_logic;
  SIGNAL RdEn   : std_logic;
  SIGNAL WrEn   : std_logic;


  -- Component Declarations
  COMPONENT ipsgen
  GENERIC (
    ADDR_WIDTH   : integer range 16 downto 8 := 8;
    BASE_ADDR    : unsigned(15 DOWNTO 0)     := x"0070";
    Nbps_default : integer range 63 downto 1 := 10;
    NC0_default  : integer                   := 10**6
  );
  PORT (
    ExpAddr  : IN     std_logic_vector (ADDR_WIDTH-1 DOWNTO 0);
    RdEn     : IN     std_logic ;
    WData    : IN     std_logic_vector (15 DOWNTO 0);
    WrEn     : IN     std_logic ;
    BdEn     : OUT    std_logic ;
    BdWrEn   : OUT    std_logic ;
    IPS      : OUT    std_logic ;
    RData    : OUT    std_logic_vector (15 DOWNTO 0);
    clk      : IN     std_logic ;
    ExpReset : IN     std_logic ;
    PPS      : IN     std_logic ;
    IPnum    : OUT    std_logic_vector (5 DOWNTO 0)
  );
  END COMPONENT ipsgen;
  COMPONENT subbus_io
  GENERIC (
    USE_BD_WR_EN : std_logic := '0'
  );
  PORT (
    BdEn   : IN     std_logic;
    BdWrEn : IN     std_logic;
    ExpRd  : IN     std_logic;
    ExpWr  : IN     std_logic;
    F8M    : IN     std_logic;
    ExpAck : OUT    std_logic;
    RdEn   : OUT    std_logic;
    WrEn   : OUT    std_logic
  );
  END COMPONENT subbus_io;

  -- Optional embedded configurations
  -- pragma synthesis_off
  FOR ALL : ipsgen USE ENTITY BCtr_lib.ipsgen;
  FOR ALL : subbus_io USE ENTITY BCtr_lib.subbus_io;
  -- pragma synthesis_on


BEGIN

  -- Instance port mappings.
  ips_def : ipsgen
    GENERIC MAP (
      ADDR_WIDTH   => ADDR_WIDTH,
      BASE_ADDR    => BASE_ADDR,
      Nbps_default => 10,
      NC0_default  => 10**7
    )
    PORT MAP (
      ExpAddr  => ExpAddr,
      RdEn     => RdEn,
      WData    => WData,
      WrEn     => WrEn,
      BdEn     => BdEn,
      BdWrEn   => BdWrEn,
      IPS      => IPS,
      RData    => RData,
      clk      => clk,
      ExpReset => ExpReset,
      PPS      => PPS,
      IPnum    => IPnum
    );
  subbus : subbus_io
    GENERIC MAP (
      USE_BD_WR_EN => '1'
    )
    PORT MAP (
      ExpRd  => ExpRd,
      ExpWr  => ExpWr,
      ExpAck => ExpAck,
      F8M    => clk,
      RdEn   => RdEn,
      WrEn   => WrEn,
      BdEn   => BdEn,
      BdWrEn => BdWrEn
    );

END ARCHITECTURE struct;
